### ISSUE TITLE
Alberta decode success. Is validation possible?

### ISSUE THREAD

**Issue by mungewell** [cvmiller/bc-covid-card-decoder#1]
Quick note, I was able to decode the "SHC:/" data from the Alberta QR code. Unfortunately it seems that my Xubuntu doesn't have access to 'pyzbar', I had to force the QRData in directly.

Once the public keys are available would it be possible to add a validation stage?

**Comment by mungewell** [comment]
BTW the BC public keys are (apparently) available here:
https://github.com/bcgov/BCVAX-iOS/blob/main/VaccineCard/VaccineCard/seed/smarthealthcard.phsa.ca~v1~issuer~.well-known~jwks.json

**Comment by cvmiller** [comment]
I wasn't planning on doing a validation, I was more interested in just what the Province was putting into the QR code. But I'll think more about that aspect of it.

As to Xubuntu not having a package for pyzbar, that is unfortunate.  Have you tried looking for `python3-zbar` which I see on one of my Ubuntu 20.04 systems

**Comment by mungewell** [comment]
It you do device to implement, this is (apparently) Alberta's public key.
https://github.com/billylo1/covidpass/pull/36/files

**Comment by cvmiller** [comment]
After giving this issue some thought, I have decided to NOT include validation. That was not part of the original goal of writing this program. I was interested in what the payload of the QR code contained. There are many Apps out there, including from Alberta & BC which will do validation.

If you feel this has not been addressed to your satisfaction, please feel free to re-open this issue. Closing.
